# Generated by Django 3.1 on 2020-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0019_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img/', verbose_name='Обложка'),
        ),
    ]
