# Generated by Django 3.1 on 2020-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0020_auto_20200902_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='img/', verbose_name='Обложка'),
        ),
    ]
