# Generated by Django 3.1 on 2020-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0023_userprofile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=15, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='can_create',
            field=models.BooleanField(default=False, verbose_name='Может добавлять книги'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Может удалять книги'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='can_manage_readers',
            field=models.BooleanField(default=False, verbose_name='Управлять другими читателями'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='can_manage_self',
            field=models.BooleanField(default=True, verbose_name='Может брать и возвращиять книги'),
        ),
    ]
