# Generated by Django 3.1 on 2020-09-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0024_auto_20200913_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
