# Generated by Django 3.1 on 2020-09-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0033_auto_20200913_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rights',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_readers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_self',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
