# Generated by Django 3.1 on 2020-09-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0035_auto_20200914_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_manage_readers',
            new_name='can_manage_library',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_manage_self',
        ),
    ]
