# Generated by Django 3.1 on 2020-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0038_book_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='profile',
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readers', to='books_shelf.Profile', verbose_name='Читатели'),
        ),
    ]
