# Generated by Django 3.1 on 2020-09-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0039_auto_20200916_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
