# Generated by Django 3.1 on 2020-09-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0041_auto_20200916_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
